version: '3.7'
services:
  fuse_video_steamer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test
    image: drive-test-fuse-app
    network_mode: container:wgcf
      # privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - ./fuse_video_steamer:/app/data:rshared
      - ./database.db:/database.db
    devices:
      - /dev/fuse:/dev/fuse:rwm
    pid: host
    command: "/app/data RD_TOKEN_HERE"
