services:
  fuse-app:
    build: .
    container_name: fuse-go-app
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - GO_ENV=development
      - HTTP_PROXY=host.docker.internal:9090
      - HTTPS_PROXY=host.docker.internal:9090
    volumes:
      - ./database.db:/app/database.db
    stdin_open: true
    tty: true
